import numpy
import seaborn
import matplotlib.pyplot as plt
a = int(input("enter the number of values to insert: "))
numarray = []
for i in range(a):
    val = int(input("enter the value: "))
    numarray.append(val)
b = numpy.array(numarray)
for i in numpy.nditer(b):
    print(i)
for i, j in numpy.ndenumerate(b):
    print(i, j)
c = numpy.random.randint(20)
c = numpy.random.rand()
c = numpy.random.randint(20, size = 3)
print(c)
d = numpy.random.rand(3, 3, 3)
print(d)
e = numpy.random.choice([4, 1, 2], size = (3, 2))
print(e)
f = numpy.random.choice([5, 1, 4, 9], p = [0.2, 0, 0.5, .3], size = (4, 1, 5))
print(f)
print('permutation', numpy.random.permutation(f), 'original', f)
numpy.random.shuffle(f)
print('shuffle', f, 'shape', f.shape)
seaborn.distplot([0, 1, 2, 3, 4, 5], hist = True)
plt.show()
seaborn.distplot(numpy.random.normal(size = (10, 2)), hist = False)
plt.show()
seaborn.displot(numpy.random.normal(size = (3, 3)))
plt.show()
seaborn.displot(numpy.random.normal(size = 1000))
plt.show()
seaborn.displot(numpy.random.binomial(n = 5, p = 1, size = 10))
plt.show()
g = numpy.random.uniform(size = (3, 21))
seaborn.distplot(g)
plt.show()
h = numpy.random.logistic(loc = 71/12, scale = 2/12, size = 50)
seaborn.distplot(h)
plt.show()
i = numpy.random.multinomial(n = 2, pvals = [.7, .3], size = 200)
seaborn.distplot(i)
plt.show()
j = numpy.random.exponential(scale = 3, size = 200)
seaborn.distplot(j)
plt.show()
k = numpy.random.chisquare(df = 2, size = (3, 5, 2))
seaborn.distplot(k)
plt.show()
l = numpy.random.rayleigh(scale = 2, size = 200)
seaborn.distplot(l)
plt.show()
m = numpy.random.uniform(size = (2, 3))
seaborn.displot(m)
plt.show()
n = numpy.random.poisson(lam = 20, size = 2)
seaborn.displot(n)
plt.show()
o = numpy.random.pareto(a = 2, size = (200, 1, 1))
seaborn.distplot(o)
plt.show()
p = numpy.random.zipf(a = 3, size = (3, 7, 2))
seaborn.distplot(p)
plt.show()
